Configure architecture flags through the configure script (#137)
* Have the `configure` script parse command line arguments and generate
an include file for the Makefile (`config.gen.mk`).
* Pass the architecture-specific CFLAGS and LDFLAGS through that file
(`--arch` argument).
* Add some additional command line arguments to the `configure' script
to cover current use cases ('--cc', '--debug', '--werror').
* Adapt the GitHub Actions workflow to make use of these new arguments.

This is preparation work for x86_64 support.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Copyright (C) 2023 Philippe Aubertin.
 # All rights reserved.
@@ -33,8 +33,80 @@ ZLIB=userspace/lib/zlib
 BZIP2=userspace/lib/bzip2
 
 CFLAGS="-std=c99 -ffreestanding -I../../../include"
-ARCH="-m32"
 
+# -----------------------------------------------------------------------------
+#  Process command line arguments
+# -----------------------------------------------------------------------------
+arch=i386
+CC=gcc
+DEBUG=0
+WERROR=""
+
+while [ $# -ge 1 ]
+do
+    case "$1" in
+        --arch)
+            shift
+            if [ ! $# -ge 1 ]
+            then
+                echo "*** ERROR: no architecture name specified for --arch"
+                exit 1
+            fi
+            arch=$1
+            shift
+            ;;
+        --cc)
+            shift
+            if [ ! $# -ge 1 ]
+            then
+                echo "*** ERROR: no value specified for --cc"
+                exit 1
+            fi
+            CC=$1
+            shift
+            ;;
+        --debug)
+            DEBUG=1
+            shift
+            ;;
+        --werror)
+            WERROR="-Werror"
+            shift
+            ;;
+        *)
+            echo "*** ERROR: unknown argument: $1"
+            exit 1
+            ;;
+    esac
+done
+
+case "$arch" in
+    i386|i686)
+        ARCH_CFLAGS="-m32 -march=pentium -mtune=generic"
+        ARCH_LDFLAGS="-Wl,-m,elf_i386"
+        ;;
+    *)
+        echo "*** ERROR: unknown architecture name: $arch"
+        exit 1
+        ;;
+esac
+
+# -----------------------------------------------------------------------------
+#  Generate config.gen.mk
+# -----------------------------------------------------------------------------
+echo "Generating config.gen.mk"
+
+cat <<EOF > config.gen.mk
+CONFIG_CC=$CC
+CONFIG_CFLAGS_ARCH=$ARCH_CFLAGS
+CONFIG_DEBUG=$DEBUG
+CONFIG_LDFLAGS_ARCH=$ARCH_LDFLAGS
+CONFIG_WERROR=$WERROR
+EOF
+
+# -----------------------------------------------------------------------------
+#  Configure zlib
+# -----------------------------------------------------------------------------
 echo "Configuring zlib in $ZLIB"
 
 if [ ! -f "$ZLIB/zlib.h" ]; then
@@ -53,8 +125,11 @@ fi
 echo "*** Please ignore any warning about vsnprintf() not being found in stdio.h."
 echo "*** Jinue does not use the part of the code in zlib where that warning is relevant."
 
-(cd $ZLIB; CFLAGS="$CFLAGS" ./configure --solo --static --warn --const --archs="$ARCH")
+(cd $ZLIB; CFLAGS="$CFLAGS $ARCH_CFLAGS" ./configure --solo --static --warn --const)
 
+# -----------------------------------------------------------------------------
+#  Configure bzip2
+# -----------------------------------------------------------------------------
 echo "Configuring bzip2 in $ZLIB"
 
 if [ ! -f "$BZIP2/bzlib.h" ]; then
@@ -80,7 +155,7 @@ echo "***"
 # There is no configure script for bzip2 but the CFLAGS are hardcoded in the
 # Makefile, so let's patch them there. Let's also remove code related to
 # compression to reduce size and the number of compiler warnings.
-(cd $BZIP2 ; (cat << "EOF") | sed -e "s@%%%-CFLAGS-%%%@$CFLAGS $ARCH@" | patch -Np1 -r-
+(cd $BZIP2 ; (cat << "EOF") | sed -e "s@%%%-CFLAGS-%%%@$CFLAGS $ARCH_CFLAGS@" | patch -Np1 -r-
 diff --git a/Makefile b/Makefile
 index b0fef95..4987a38 100644
 --- a/Makefile
