Decompress RAM disk (#36)
Have the loader decompress the RAM disk image.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,6 @@
-# Copyright (C) 2019 Philippe Aubertin.
+#!/bin/sh
+
+# Copyright (C) 2023 Philippe Aubertin.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -26,12 +28,21 @@
 # ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-linux16 /boot/jinue \
-    serial_enable=yes \
-    serial_dev=/dev/ttyS0 \
-    DEBUG_DUMP_MEMORY_MAP=1 \
-    DEBUG_DUMP_SYSCALL_IMPLEMENTATION=1 \
-    DEBUG_DO_REBOOT=1 \
-    RUN_TEST_IPC=1
-initrd16 /boot/jinue-initrd.tar.gz
-boot
+
+ZLIB=userspace/lib/zlib
+
+echo "Configuring zlib in $ZLIB"
+
+if [ ! -f "$ZLIB/zlib.h" ]; then
+    echo ""
+    echo "*** ERROR: zlib.h not found in $ZLIB."
+    echo "*** "
+    echo "*** Did you forget to initialize the git submodules when you cloned the repository? "
+    echo "*** See README.md for detail."
+    exit 1
+fi
+
+echo "*** Please ignore any warning about vsnprintf() not being found in stdio.h."
+echo "*** Jinue does not use the part of the code in zlib where that warning is relevant."
+
+(cd $ZLIB; CFLAGS='-std=c99 -ffreestanding -I../../../include' ./configure --solo --static --warn --const --archs="-m32")
